### ISSUE TITLE
Can't generate world

### ISSUE THREAD

**Issue by AldeRoberge** [Chaika9/MinecraftUnity#1]
Hello Chaika,

I tried to generate a world but it was stuck at "Generating world..."

![Uploading image.png…]()

Does this happen to you too?

**Comment by AldeRoberge** [comment]
![image](https://user-images.githubusercontent.com/4276275/222944403-505e5c4e-e076-4c38-b3fb-2c6e41f7f52b.png)

**Comment by Chaika9** [comment]
Hello,
Are you wait well on the Game Tab? The generation take time x)

**Comment by AldeRoberge** [comment]
I waited a solid 10-15 seconds, maybe I was too quick!

**Comment by Chaika9** [comment]
Yes, it's possible. Please let me know if the problem persists. (with more time)
